import React from 'react';
import './About.css';
import Footer from '../../components/Footer/Footer';

const values = [
  {
    icon: 'verified',
    title: 'Evidence First',
    desc: 'Every verdict is strictly bound to retrievable, citable sources. We never extrapolate beyond what the evidence supports.',
  },
  {
    icon: 'visibility',
    title: 'Radical Transparency',
    desc: 'Full reasoning chains are exposed to the user. Nothing is hidden inside a black box — every score and decision is explainable.',
  },
  {
    icon: 'balance',
    title: 'Epistemic Humility',
    desc: 'When evidence is insufficient or contradictory, TruthTrace returns "Unverifiable" rather than fabricating a confident answer.',
  },
];

const techStack = [
  { icon: 'hub', label: 'RAG Pipeline' },
  { icon: 'psychology', label: 'LLM Reasoning' },
  { icon: 'manage_search', label: 'Semantic Search' },
  { icon: 'database', label: 'Vector Database' },
  { icon: 'article', label: 'Document Parsing' },
  { icon: 'school', label: 'Peer-review Sources' },
  { icon: 'code', label: 'Open API' },
];

function About() {
  return (
    <>
      <main className="about-page">
        {/* Hero */}
        <section className="about-hero">
          <h1 className="about-hero__title">About TruthTrace</h1>
          <p className="about-hero__subtitle">
            TruthTrace is a research-grade fact-verification system built on the principle that truth is
            discoverable through evidence, not generated by models. We combine retrieval-augmented generation
            with transparent reasoning to deliver verifiable answers to complex claims.
          </p>
        </section>

        {/* Values */}
        <section style={{ marginBottom: '80px' }}>
          <h2 className="about-section-title">Our Core Values</h2>
          <div className="about-values">
            {values.map((v) => (
              <div key={v.title} className="about-value-card">
                <div className="about-value-icon">
                  <span className="material-symbols-outlined">{v.icon}</span>
                </div>
                <h3 className="about-value-title">{v.title}</h3>
                <p className="about-value-desc">{v.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Technology */}
        <section style={{ marginBottom: '80px' }}>
          <h2 className="about-section-title">Technology Stack</h2>
          <div className="about-tech-stack">
            {techStack.map((t) => (
              <div key={t.label} className="about-tech-tag">
                <span className="material-symbols-outlined" style={{ fontSize: '16px' }}>{t.icon}</span>
                {t.label}
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="about-cta">
          <h2 className="about-cta__title">Ready to verify a claim?</h2>
          <p className="about-cta__subtitle">
            Use TruthTrace to ground your research in evidence, not assumptions.
          </p>
          <a href="/" className="about-cta__btn">
            <span className="material-symbols-outlined" style={{ fontSize: '20px' }}>manage_search</span>
            Start Verifying
          </a>
        </section>
      </main>
      <Footer />
    </>
  );
}

export default About;
